language: python

python:
    - 3.4
    - 3.5
    - 3.6
    - 3.7
    - 3.8
    - 3.9

before_install:
  - pip list

install:
  # install deps
  - pip install -r requirements.txt
  - pip install python-coveralls

script:
  - PYTHONPATH=src py.test --cov-report term-missing --cov-config .coveragerc --cov=scan_pdf

after_success:
  - coveralls
  - ls -la
